kind: Deployment
apiVersion: apps/v1
metadata:
  name: scmchangestreamnew
  labels:
    app: scmchangestreamnew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scmchangestreamnew
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: scmchangestreamnew
      labels:
        app: scmchangestreamnew
    spec:
     containers:
     - name: scmchangestreamnew
       image: ghcr.io/prasantabarik/del/image:latest
       imagePullPolicy: Always
       resources:
         requests:
           memory: 1Gi
           cpu: 500m
         limits:
           memory: 2Gi
           cpu: 1000m
