name: Deploy to AKS Cluster
on:
  pull_request:
    branches:
    - master
  push:
    branches: 
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
         
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: WeEuS01AKSDEP01
        resource-group: WeEu-S01-Dev-Rsg-Akscn-DEP-01
        
 #   - uses: Azure/k8s-create-secret@v1
 #     with:
 #       container-registry-url: cloudlifeacr.azurecr.io
 #       container-registry-username: ${{ secrets.ACR_USERNAME }}
 #       container-registry-password: ${{ secrets.ACR_PASSWORD }}
 #       secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        namespace: fromgh
        manifests: |
          manifests/deployment.yaml
 #         manifests/service.yaml
        images: |
          docker.pkg.github.com/prasantabarik/del/image:latest
     #     cloudlifeacr.azurecr.io/k8sflask:${{ github.sha }}
           
#        imagepullsecrets: |
#          k8s-secret
